# Meta opts:
## IO
save_data: generated/dynamic.ex0
overwrite: False

### vocab:
src_vocab: data/vocab-train.src
tgt_vocab: data/vocab-train.tgt
src_vocab_size: 32000
tgt_vocab_size: 32000
vocab_size_multiple: 8
src_words_min_frequency: 10
tgt_words_min_frequency: 10
share_vocab: True

### Transform related opts:
#### Subword
src_subword_model: examples/subword.spm.model
tgt_subword_model: examples/subword.spm.model
subword_nbest: 1
subword_alpha: 0.0
src_subword_type: sentencepiece
tgt_subword_type: sentencepiece
onmttok_kwargs: "{'mode': 'aggressive', 'spacer_annotate': True}"
#### Sampling
switchout_temperature: 1.0
tokendrop_temperature: 1.0
tokenmask_temperature: 1.0
#### Filter
src_seq_length: 300
tgt_seq_length: 300
#### BART
permute_sent_ratio: 0.0
rotate_ratio: 0.0
insert_ratio: 0.0
random_ratio: 0.0
mask_ratio: 0.0
mask_length: subword
poisson_lambda: 3.0
replace_length: 1

# Corpus opts:
data:
    corpus_1:
        path_src: data/src-train.txt
        path_tgt: data/tgt-train.txt
        transforms: [tokenmask, tokendrop, onmt_tokenize, prefix, filtertoolong]
        weight: 5
        src_lang: en
        tgt_lang: de
    valid:
        path_src: data/src-val.txt
        path_tgt: data/tgt-val.txt
        transforms: [onmt_tokenize, prefix]
        src_lang: en
        tgt_lang: de
