# data_config: examples/onmt.dynamic.data_config.yaml
save_model: foo
keep_checkpoint: 50
save_checkpoint_steps: 4000
average_decay: 0.0001
seed: 2345
report_every: 100
train_steps: 100000
valid_steps: 4000

queue_size: 10000
bucket_size: 32768
world_size: 6
gpu_ranks: [0, 1, 2, 3, 4, 5]
batch_type: "tokens"
batch_size: 1560
valid_batch_size: 8
batch_size_multiple: 1
max_generator_batches: 0
accum_count: [3, 6, 12]
accum_steps: [0, 15000, 30000]

model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 6000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
share_decoder_embeddings: true
share_embeddings: true
